name: Release

on:
  workflow_dispatch:
    inputs:
      chart-version:
        required: true
        type: string
        description: Chart Version
      proxy-version:
        required: true
        type: string
        description: Evaluation Proxy Version

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Helm Lint
        run: helm lint charts/evaluation-proxy

      - name: Set Chart Version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'version: .*'
          replace: 'version: ${{ github.event.inputs.chart-version }}'
          include: 'charts/evaluation-proxy/Chart.yaml'
          regex: true

      - name: Set Chart Version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'appVersion: ".*"'
          replace: 'appVersion: "${{ github.event.inputs.chart-version }}"'
          include: 'charts/evaluation-proxy/Chart.yaml'
          regex: true

      - name: Release Chart
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
